# ============================================================================ #
# Proximity devphp framework config
# ============================================================================ #
admin:
  login: admin
  password: *****

# ============================================================================ #
# Multilang options
# ============================================================================ #
multilang:
  default: nl-BE
  # dir: assets/locales/ # from root, default is assets/locales/

# ============================================================================ #
# TESTING
# ============================================================================ #
verbose: true #outputs logs
