# ============================================================================ #
# Proximity devphp framework config
# ============================================================================ #
admin:
  login: admin
  password: ****

# ============================================================================ #
# Multilang
# ============================================================================ #
multilang:
  languages:
    nl: translationNL
    fr: translationFR

